name = "SyntheticObjects"
uuid = "e7028c27-0967-45e9-8fdb-dbc10ccb2b0a"
authors = ["Hossein Zarei Oshtolagh"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
