name: Workflow for Codecov SyntheticObjects.jl
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: codecov/codecov-action@v4
      with:
        fail_ci_if_error: true # optional (default = false)
        flags: unittests # optional
        name: codecov-umbrella # optional
        token: ${{ secrets.CODECOV_TOKEN }} # required
        verbose: true # optional (default = false)